# Generated by Django 4.1 on 2022-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='undesire',
            field=models.BooleanField(default=True),
        ),
    ]
