# Generated by Django 4.1 on 2022-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_undesire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='undesire',
        ),
    ]
